var tableauQuestion = [
    {   question : "إذا كانت السرعة 120 كم/س، وعلى وشك الوصول إلى منطقة سكنية يجب عليك:",
        propositionA : "زيادة السرعة",
        propositionB : "المحافظة على السرعة، إذا كنت لاترغب في تجاوز مركبة أمامك",
        propositionC : "أخفف السرعة",
        propositionD : "القيادة عكس السير",
        reponse : "C"},

    {   question : "إذا كنت تنعطف يمين عند إشارة المرور وصادفت مشاة يعبرون الطريق، ماذا تفعل؟",
        propositionA : "اقطع طريق المشاة ولا انتظر",
        propositionB : "أبلغ الشرطة فورا",
        propositionC : "اتوقف وانتظر المشاة يعبرون الطريق",
        propositionD : "أطلق النار على المشاة وأكمل القيادة",
        reponse : "C"},

    {   question : "حدود السرعة داخل المناطق السكنية هي؟ كم/ساعة",
        propositionA : "50",
        propositionB : "80",
        propositionC : "100",
        propositionD : "120",
        reponse : "A"},

  {   question : "إذا طلب منك رجال الشرطة التوقف، ماذا تفعل؟",
        propositionA : "اهدئ السرعة",
        propositionB : "اقف على يمين الطريق",
        propositionC : "أنتظر داخل المركبة",
        propositionD : "جميع ماسبق",
        reponse : "D"},

  {   question : "حدود السرعة في الطرق السريعة هي؟ كم/ساعة",
        propositionA : "80",
        propositionB : "100",
        propositionC : "120",
        propositionD : "150",
        reponse : "C"},

  {   question : "متى يمكنك قطع إشارة المرور",
        propositionA : "عند اللون الأخضر",
        propositionB : "عند خلو التقاطع",
        propositionC : "عند التأكد عدم وجود دورية شرطة",
        propositionD : "عند اللون الأخضر و/أو اللون الأحمر والأنعطاف يمين",
        reponse : "D"},

  {   question : "إذا طلب الشرطي اثبات الشخصية، ماذا تفعل؟",
        propositionA : "اصدم الشرطي وأكمل طريقي",
        propositionB : "أهدد الشرطي وأقتله بعد 30 ثانيه",
        propositionC : "أطنش وأكمل قيادة المركبة",
        propositionD : "أقدم الهوية للشرطي",
        reponse : "D"},

  {   question : "إذا طلب منك شخص الدوران بشكل غير قانوني، ماذا تفعل؟",
        propositionA : "أسمع كلامه وما اهتم في العلامات المرورية",
        propositionB : "أتأكد أول أن مافي دورية شرطة",
        propositionC : "أكمل طريقي لأن ممنوع الدوران",
        propositionD : "أهدد الشخص وأقتله",
        reponse : "C"},

  {   question : "إذا تم حجز مركبتك بسبب مخالفة مرورأو تعطلت في طريق، ماذا تفعل؟",
        propositionA : "أتصل في الميكانيكي لرفع المركبة عن الطريق وإصلاحها",
        propositionB : "أتصل في التاكسي لتوفير مواصلات بديله",
        propositionC : "أتصل في أحد اصدقائي أو الشرطة للمساعدة",
        propositionD : "أي مما سبق",
        reponse : "D"},

  {   question : "في حالة مرور موكب رسمي أو مركبة طوارئ، ماذا تفعل؟",
        propositionA : "أفجر الموكب",
        propositionB : "اتصل في الشرطة",
        propositionC : "لا أفعل شيء",
        propositionD : "أفسح الطريق للموكب أو مركبات الطوارئ",
        reponse : "D"},
]
